/**
 * Re-encode the content photos in public/ so they weigh what their pixel
 * dimensions justify.
 *
 * Why this exists. An audit on 2026-09-07 found the photos were saved at or
 * near quality 100, which on a photographic JPEG buys nothing a person can
 * see and costs three to four times the bytes. Notary.jpg was 437 KB at
 * 1179x411; a correctly encoded photo that size is well under 100 KB. The
 * heroes are CSS background images, so they are the LCP element on every
 * photo-hero page, and 58% of the site's traffic arrives on a phone from
 * Google Search.
 *
 * ## The one rule this script obeys
 *
 * **Nothing about how the site looks may change.** The owner's instruction
 * was to keep the format, the fonts and the colours the same. So:
 *
 * - Dimensions are never touched. Every image comes out the exact pixel size
 *   it went in, which means no CSS, no width/height attribute and no layout
 *   anywhere can be affected by running this.
 * - JPEG stays JPEG. No WebP, no AVIF, no format switch. Those are a further
 *   saving and they are deliberately not taken here, because they change what
 *   the browser is served and that was not what was asked for.
 * - Quality comes off QUALITY_LADDER, and the choice is verified rather than
 *   assumed. For each file the script encodes, measures the mean per-channel
 *   difference against the original, and climbs the ladder until that
 *   difference is inside MAX_MEAN_DELTA. A file that cannot get there at any
 *   quality is left untouched and reported, so this can never quietly
 *   degrade a photo to save bytes.
 *
 * ## Not part of `npm run build`
 *
 * Same reasoning as generate-og-images.mjs: the outputs are committed, so
 * this runs only when photos are added or replaced. Running it twice is safe
 * but pointless -- the second pass re-encodes an already-encoded file, so it
 * skips anything it cannot improve by at least MIN_SAVING_PCT.
 *
 *     node scripts/optimize-images.mjs           # report only, writes nothing
 *     node scripts/optimize-images.mjs --write   # actually re-encode
 */

import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const PUBLIC_DIR = "public";

/**
 * Tried in order, first one that comes in under MAX_MEAN_DELTA wins.
 *
 * 82 is right for ordinary photographic content and is what most of these
 * files take. Notary.jpg is the reason the ladder exists: it is unusually
 * fine-detailed (channel stdev around 60, high sharpness) and was stored at
 * 0.92 bytes per pixel, effectively lossless. At 82 its mean delta was 3.37,
 * over the limit, so the first version of this script skipped it -- and it
 * was the largest file on the site at 437 KB. Escalating settles it at 88,
 * which still takes it from 437 KB to 108 KB while staying inside the
 * threshold.
 *
 * Escalating rather than hand-listing an override per file matters because
 * this script is committed and will be run again on photos nobody has seen
 * yet.
 */
const QUALITY_LADDER = [82, 88, 92, 95];

/** Keep a re-encode only if it saves at least this much. */
const MIN_SAVING_PCT = 8;

/**
 * Mean absolute per-channel difference, 0-255, above which the re-encode is
 * rejected as visibly different. Imperceptible re-encodes of photographic
 * content land around 0.5-1.5; anything past 3 is worth looking at by eye.
 */
const MAX_MEAN_DELTA = 3;

/**
 * Left alone on purpose.
 *
 * - The og/ cards and og-image.jpg are generated by generate-og-images.mjs
 *   and would be overwritten by it anyway; that script owns their encoding.
 * - PNG is excluded wholesale. The logos and favicons need their alpha, and
 *   zelle-qr.png is a scannable code where lossy artefacts are a functional
 *   problem, not a cosmetic one.
 */
const SKIP = new Set(["og-image.jpg"]);
const isCandidate = (f) => /\.jpe?g$/i.test(f) && !SKIP.has(f);

/** Mean absolute difference across all channels of two same-size images. */
async function meanDelta(beforeBuf, afterBuf) {
  const a = await sharp(beforeBuf).raw().toBuffer({ resolveWithObject: true });
  const b = await sharp(afterBuf).raw().toBuffer({ resolveWithObject: true });
  if (a.data.length !== b.data.length) return Infinity;

  let total = 0;
  for (let i = 0; i < a.data.length; i++) total += Math.abs(a.data[i] - b.data[i]);
  return total / a.data.length;
}

const write = process.argv.includes("--write");
const files = (await readdir(PUBLIC_DIR)).filter(isCandidate).sort();

let beforeTotal = 0;
let afterTotal = 0;
const rows = [];

for (const name of files) {
  const file = path.join(PUBLIC_DIR, name);
  const original = await readFile(file);
  const { width, height } = await sharp(original).metadata();

  // No resize, no rotate, no strip of anything but the metadata a browser
  // never reads. Same pixels, fewer bytes.
  let reencoded = null;
  let delta = Infinity;
  let quality = null;

  for (const q of QUALITY_LADDER) {
    const candidate = await sharp(original)
      .jpeg({ quality: q, mozjpeg: true, progressive: true })
      .toBuffer();
    const d = await meanDelta(original, candidate);
    if (d <= MAX_MEAN_DELTA) {
      reencoded = candidate;
      delta = d;
      quality = q;
      break;
    }
    // Remember the closest attempt so the report can say how far off it was.
    if (d < delta) delta = d;
  }

  const savingPct = reencoded
    ? ((original.length - reencoded.length) / original.length) * 100
    : 0;

  let action;
  if (!reencoded) action = `SKIP (delta ${delta.toFixed(2)} at every quality)`;
  else if (savingPct < MIN_SAVING_PCT) action = "SKIP (already lean)";
  else action = write ? `written q${quality}` : `would write q${quality}`;

  if (action.startsWith("written")) await writeFile(file, reencoded);

  const kept = action.startsWith("written") || action.startsWith("would write");
  beforeTotal += original.length;
  afterTotal += kept ? reencoded.length : original.length;

  rows.push({
    name,
    dims: `${width}x${height}`,
    before: original.length,
    after: kept ? reencoded.length : original.length,
    delta,
    action,
  });
}

const kb = (n) => `${(n / 1024).toFixed(0)} KB`;

console.log(`\n${write ? "Re-encoding" : "Dry run"} at quality ${QUALITY_LADDER[0]} or above, dimensions unchanged\n`);
for (const r of rows) {
  const pct = r.before === r.after ? "" : `  -${(((r.before - r.after) / r.before) * 100).toFixed(0)}%`;
  console.log(
    `  ${r.name.padEnd(32)} ${r.dims.padEnd(12)} ` +
      `${kb(r.before).padStart(8)} -> ${kb(r.after).padStart(8)}${pct.padEnd(7)} ` +
      `delta ${r.delta.toFixed(2).padStart(5)}  ${r.action}`
  );
}
console.log(
  `\n  Total ${kb(beforeTotal)} -> ${kb(afterTotal)} ` +
    `(-${(((beforeTotal - afterTotal) / beforeTotal) * 100).toFixed(0)}%)\n`
);
if (!write) console.log("  Nothing written. Re-run with --write to apply.\n");
